### ISSUE TITLE
Parse error when StrEnum is unioned with int in dataclass field

### ISSUE THREAD

**Issue by BrendanMartin** [rnag/dataclass-wizard#118]
* Dataclass Wizard version: 0.22.3
* Python version: 3.11
* Operating System: Windows 10

### Description

I'm trying to have a dataclass field take on either a `StrEnum` or an `int`. Using `from_dict()` works when StrEnum is used, but unioned with int throws a parse error.

### What I Did

In the examples below, `Example` works but `Example2` throws a parse error:

```python
class Value(StrEnum):
    DEFAULT = 'default'

@dataclass
class Example(JSONWizard):
    test: Value

# Works
d = {'test': 'default'}
example = Example.from_dict(d)


@dataclass
class Example2(JSONWizard):
    test: Value | int

# Error
d2 = {'test': 'default'}
example2 = Example2.from_dict(d2)
```

Here's the error output:
```
>       raise ParseError(
            TypeError('Object was not in any of Union types'),
            o, [p.base_type for p in self.parsers],
            tag_key=self.tag_key
        )
E       dataclass_wizard.errors.ParseError: Failure parsing field `test` in class `Example2`. Expected a type [<enum 'Value'>, <class 'int'>], got str.
E         value: 'default'
E         error: Object was not in any of Union types
E         tag_key: '__tag__'
E         json_object: '{"test": "default"}'
```

**Comment by rnag** [comment]
It's a known issue. I commented on #67,  which is AFAIK the same problem.

As it's the same issue, I am going to close this in favor of above. Will add a note that `Union` with `StrEnum` / `Enum` behaves the same way.
