### ISSUE TITLE
dataclass-wizard incompatible with Python 3.13

### ISSUE THREAD

**Issue by erikpragt-connectid** [rnag/dataclass-wizard#128]
* Dataclass Wizard version: 0.23.0
* Python version: 3.13
* Operating System: Mac

### Description

In `models.py`, there's a reference to the private function called `_create_fn`. This function has been removed in Python 3.13:

https://github.com/python/cpython/blob/2f8301cbfbdd2976d254a4a772b4879069dd4298/Lib/dataclasses.py#L491

As a result, dataclass-wizard no longer works. As a solution, maybe the `_create_fn` can be copied, or maybe a whole different approach is needed, I'm not sure.

**Comment by benjjs** [comment]
Put up https://github.com/rnag/dataclass-wizard/pull/129 to address this but will need to get @rnag's attention.

**Comment by rnag** [comment]
Hey guys, sorry for the delay. I'm looking into this now.

**Comment by rnag** [comment]
@benjjs Your PR looks good and seems it would solve the compatibility issue with 3.13. Good job! I added some notes, mostly minor stuff. Let me know when you're able to look into it, but it LGTM otherwise. Thanks!

**Comment by rnag** [comment]
Closing, as this is fixed by https://github.com/rnag/dataclass-wizard/pull/129.
