### ISSUE TITLE
Unable to save bytes in base64

### ISSUE THREAD

**Issue by felix1m** [rnag/dataclass-wizard#140]
i tried for many hours in many different approaches:
How could you add type or serializer hooks to attach a small jpg image?

The best i could come up with was:

```
    def __pre_as_dict__(self):
        # Convert bytes to base64 before serialization
        if isinstance(self.image, bytes):
            self.image = b64encode(self.image).decode('utf-8')

    def __post_init__(self):
        if isinstance(self.image, str):
            self.image = b64decode(self.image.encode('utf-8'))
```

But this has the ugly side effect to mutate the object with a type change in place on writing.

i tried many iterations of s.th. like 

```
    def load_to_bytes(o: Union[AnyStr, N], base_type: Type[Enum]) -> Enum:
        return b64decode(o.encode())

    def dump_with_bytes(o: str, *_):
        return b64encode(o).decode('utf-8')
```

But no Success.
This would also make a great documentation case for custom hooks as i could not understand the current one.

**Comment by rnag** [comment]
@felix1m Thanks for opening this issue! There is a related issue for this, #87 which I closed out.

I agree documentation on this process would be useful, as others might have similar issue with implementing custom Loader/Dumper.

In any case, I put together a working example below:

```python3
from base64 import b64decode, b64encode
from dataclasses import dataclass
from typing import Union, Text, AnyStr

from dataclass_wizard import LoadMixin, JSONWizard, DumpMixin


class MyLoadMixin(LoadMixin, DumpMixin):

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__()
        cls.register_load_hook(bytes, cls.load_to_bytes)
        cls.register_dump_hook(bytes, cls.dump_with_bytes)

    @staticmethod
    def load_to_bytes(o: Union[AnyStr, None], _: type[bytes]) -> bytes:
        return b64decode(o.encode('utf-8'))

    @staticmethod
    def dump_with_bytes(o: bytes, *_) -> str:
        return b64encode(o).decode('utf-8')


@dataclass
class A(JSONWizard, MyLoadMixin):

    my_str: str
    image: bytes


a1 = A('test', b'test')
print(repr(a1))

d = a1.to_dict()
print(d)

a2 = A.from_dict(d)
print(repr(a2))

assert a1 == a2
```

Try it out and let me know if it resolves your issue. I agree documentation would need to be updated. I would welcome a PR to achieve this.

**Comment by rnag** [comment]
Just a note of how i'm envisioning `v1` (and `v1` opt-in which is now available) to resolve this issue.

With the next major release, `LoadMixin` as shown above, won't be needed for `bytes` type, which will be fully supported OOTB.

Example which should be supported, as of the next minor release:

```python3
@dataclass
class A(JSONWizard, debug=True):

    class _(JSONWizard.Meta):
        v1 = True
        key_transform_with_dump = 'SNAKE'

    my_str: str
    image: bytes


a1 = A('test', b'testing')

d = a1.to_dict()
assert d == {'my_str': 'test', 'image': 'dGVzdGluZw=='}

a2 = A.from_dict(d)
assert a1 == a2 == A(my_str='test', image=b'testing')
```

**Comment by dlenskiSB** [comment]
@rnag, I've run into this issue as well. 

I think the reason that the current behavior is very confusing is because [the docs on type hooks](https://dataclass-wizard.readthedocs.io/en/stable/advanced_usage/type_hooks.html) don't say anything about needing to subclass the `LoadMixin`/`DumpMixin` in order to be able to override the `load_to`/`dump_with` methods.

**Comment by rnag** [comment]
> It appears that v1 supports _deserialization_ of `bytes`-as-base64 correctly, but not serialization 😕
> [...]

Hi @dlenskiSB, that's a good point. I noticed the same behavior a while after I posted the comment. The reason is that serialization isn't implemented for `v1` yet, and the default serialization process doesn't support `bytes` either.

It should be a simple enough fix. I'll put together a patch/minor release shortly to address this. Stay tuned!

> @rnag, I've run into this issue as well.
> 
> I think the reason that the current behavior is very confusing is because [the docs on type hooks](https://dataclass-wizard.readthedocs.io/en/stable/advanced_usage/type_hooks.html) don't say anything about needing to subclass the `LoadMixin`/`DumpMixin` in order to be able to override the `load_to`/`dump_with` methods.

Also, a good point. I do note that subclassing is required for `LoadMixin`/`DumpMixin`. I agree the docs are confusing, and I'll need to update them to clarify on it.

**Comment by rnag** [comment]
@dlenskiSB  This may take me some time, for now you can use `DumpMixin` as shown below, for a workaround:

```python3
from base64 import b64encode
from dataclasses import dataclass
from typing_extensions import Buffer
from dataclass_wizard import JSONWizard, DumpMixin


@dataclass
class Foo(JSONWizard, DumpMixin):

    class _(JSONWizard.Meta):
         v1 = True

    b: bytes = None
    s: str = None

    @staticmethod
    def dump_with_bytes(o: Buffer, *_):
        return b64encode(o).decode()


Foo.register_dump_hook(bytes, Foo.dump_with_bytes)


data = {'b': 'AAAA', 's': 'foobar'}

foo = Foo.from_dict(data)
print(foo.to_json())

# Check data consistency
assert Foo.from_dict(foo.to_dict()).to_dict() == data
```

**Comment by rnag** [comment]
@dlenskiSB I'll add a `TODO` item for updating the docs. I agree that clarifying on support for de/serialization behavior for new or existing types is desirable.

As of **v0.34.0**, `bytes` and `bytearray` should be supported OOTB with `v1` opt-in:

```python3
from dataclasses import dataclass
from dataclass_wizard import JSONWizard


@dataclass
class Foo(JSONWizard):

    class _(JSONWizard.Meta):
         v1 = True

    b: bytes = None
    s: str = None


data = {'b': 'AAAA', 's': 'foobar'}

foo = Foo.from_dict(data)
print(foo.to_json())

# Check data consistency
assert Foo.from_dict(foo.to_dict()).to_dict() == data
```
