### ISSUE TITLE
Datetime default sql value cant be parsed

### ISSUE THREAD

**Issue by adv-zl** [rnag/dataclass-wizard#72]
* Dataclass Wizard version: 0.22.2
* Python version: 3.9
* Operating System: Osx

### Description

I have sqllite db with model:
```

@dataclass
class Account(db.Model):
    id: int
    login: str

    time_added: datetime

    __tablename__ = 'accounts'
    __table_args__ = {'extend_existing': True}

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    login = db.Column(db.String(length=100), nullable=True)
 
    time_added = db.Column(db.DateTime, default=datetime.now)
```

### What I Did

```
        DumpMeta(key_transform='SNAKE').bind_to(Account)
        my_dict = asdict(self)
        print(my_dict)

```

> {'id': 1, 'login': '', 'time_added': '2022-10-22T18:38:59.950548'}

Why time_added cant be parsed and returns as string?

I want to set custom format like '%d.%m %H:%M'. How is it possible to do it?

**Comment by rnag** [comment]
Hi @adv-zl , sorry for delayed response -

I don't have a great solution for this, as per-field custom datetime format for serialization would be a nice feature to have. If you would like this, please create a separate issue!

> I want to set custom format like '%d.%m %H:%M'. How is it possible to do it?

Per your ask, you could create a custom Mixin class subclassing from `DumpMixin` and then override the dump hook for `datetime` type dataclass fields.

Here's how I would do it:

```python3
from dataclasses import dataclass
from datetime import datetime

from dataclass_wizard import JSONWizard, DumpMixin


class MyDTDumper(DumpMixin):

    @staticmethod
    def dump_with_datetime(o: datetime, *_):
        return o.strftime('%d.%m %H:%M')


@dataclass
class Account(JSONWizard, MyDTDumper):
    id: int
    login: str
    time_added: datetime


d = {'id': 1, 'login': '', 'time_added': '2022-10-22T18:38:59.950548'}

a = Account.from_dict(d)
print(repr(a))

print(a.to_dict())
```

Prints:

```
Account(id=1, login='', time_added=datetime.datetime(2022, 10, 22, 18, 38, 59, 950548))
{'id': 1, 'login': '', 'timeAdded': '22.10 18:38'}
```
