### ISSUE TITLE
Question/Feature Request -- exclude None for json serialization

### ISSUE THREAD

**Issue by txjmb** [rnag/dataclass-wizard#80]
I have a json serialization need to not serialize values that are None.  Many of the defaults are None, but not all, so excluding defaults doesn't work, and I do need to serialize some of the non-None defaults.  Is there a simple way to do this with dataclass-wizard?

**Comment by rnag** [comment]
Hi @txjmb , I am pleased to say this feature request -- exclude None for JSON serialization -- has been implemented as part of `v0.30.0`! 🎉 

I even added a section on [Conditional Field Skipping](https://dataclass-wizard.readthedocs.io/en/latest/index.html#conditional-field-skipping). It's very easy to conditionally skip fields, or fields with default values, and even skip on a per-field basis.

Here is a usage of skipping "None" defaults:

```python3
from dataclasses import dataclass, field
from dataclass_wizard import JSONPyWizard, IS



@dataclass
class ExampleWithFalsy(JSONPyWizard):
    class _(JSONPyWizard.Meta):
        skip_defaults_if = IS(None)  # Skip if `None`

    my_str: 'str | None'
    my_list: list = field(default_factory=list)
    my_none: None = None

print(ExampleWithFalsy(my_str=None, my_list=[], my_none=None).to_dict())
#> {'my_str': None, 'my_list': []}
```
