### ISSUE TITLE
Throw error when dict contains fields not found in the dataclass

### ISSUE THREAD

**Issue by fakuivan** [rnag/dataclass-wizard#83]
Is it possible to throw an error whenever fields not declared in the dataclass are present in the input being parsed? Right now it seems like extra fields are just ignored.

**Comment by lmmx** [comment]
It is documented here: https://dataclass-wizard.readthedocs.io/en/latest/common_use_cases/meta.html

**Comment by rnag** [comment]
> I've found that the metaclass config `raise_on_unknown_json_key` does exactly what I need. I've found it in the following test case:
> 
> https://github.com/rnag/dataclass-wizard/blob/d59bd79dd94effe90b00e667c6ed7539c7e98b43/tests/unit/test_dump.py#L36
> 
> Any ideas of why it's not documented or why it specifically mentions JSON?

@fakuivan Good point! I've just added some dedicated documentation on this feature [here](https://dataclass-wizard.readthedocs.io/en/latest/common_use_cases/handling_unknown_json_keys.html).

Please feel free to create a PR to clarify/improve documentation further if you feel it could be useful. For now, I am closing this issue as a solution was found.

Also, if it is helpful -- I recently opened [GitHub Discussions](https://github.com/rnag/dataclass-wizard/discussions) for this project, so any future questions please post there, I will continue to monitor it going forward. Thanks! 🫡
