### ISSUE TITLE
Ability to add a custom type hook for unsupported builtin types like Path and re.Pattern

### ISSUE THREAD

**Issue by TomHodson** [rnag/dataclass-wizard#87]
* Dataclass Wizard version: 0.22.2
* Python version: 3.11.3
* Operating System: OSX 12.3

### Description

I wanted to create a type hook for `re.Pattern` following the example given [here](https://dataclass-wizard.readthedocs.io/en/latest/advanced_usage/type_hooks.html)

### What I Did
Copied the code from the link above and adapted it to my use case. However the example does two cases:
1) Overrides the loader/dumper for a known type `str`
2) Creates a loader for a custom class `MyEnum`

I would like to create a loader for a builtin class `re.compile`. I see someone has a pull request open for adding a loader for `pathlib.Path` but I don't see that you should have to support loaders for every single builtin class.  So I would like to just do it myself.

After digging around in the code I got it to work by calling `MyClass.register_load_hook(Pattern, MyClass.load_to_pattern)`. My question is: Is that the intended way this would work? If so I would be happy to open a pull request to update the docs to mention this. Otherwise it would be very cool some fancy introspection could make the call to `register_load_hook` happen automatically. 

Love this library by the way!

Example Code:
```python
from dataclasses import dataclass
from dataclass_wizard import JSONSerializable, DumpMixin, LoadMixin

import re
from re import Pattern

@dataclass
class MyClass(JSONSerializable, LoadMixin, DumpMixin):
    regex: Pattern
    my_str: str

    @staticmethod
    def load_to_str(o: str, *_) -> str:
        return o.upper()
    
    @staticmethod
    def load_to_pattern(o: Pattern, *_) -> Pattern:
        return re.compile(o)
    
# This line was not obvious to me from reading the docs
MyClass.register_load_hook(Pattern, MyClass.load_to_pattern)

data = {"my_str": "my string", "regex" : "[^/]+"}

c = MyClass.from_dict(data)
print(repr(c))
# prints:
#   MyClass(regex=re.compile('[^/]+'), my_str='MY STRING')
```

**Comment by TomHodson** [comment]
I addition I now realised that the `register_load_hook` solution does not apply recursively. I looked into a method that would allow me to apply a solution recursively. I tried subclassing `LoadMixin` and/or replacing `setup_default_loader` but couldn't get it to apply recursively. Do you recommend a way to do this?

**Comment by julian-belina** [comment]
Any Update on this? I am currently tyring to do a similar thing. I storing physical units from the library pint in a dataclass and want to load and dump these.

**Comment by Sergeant007** [comment]
Thanks for the working example, @TomHodson - saved my day

**Comment by rnag** [comment]
@TomHodson Thanks for opening this issue! This is really helpful for others, and I agree that documentation on this would be super great to have.

Also apologies, I have been super busy and haven't had a chance to look at this issue until now.

You hit the nail on the head that documentation on this is lacking! It would be great to have and I would fully welcome a PR to improve on documentation on custom type hooks.

Re. your question -

> I addition I now realised that the `register_load_hook` solution does not apply recursively. I tried subclassing `LoadMixin` and/or replacing `setup_default_loader` but couldn't get it to apply recursively. Do you recommend a way to do this?

I had a suspicion that `__init_subclass__` should save the day, so I did a quick test, and I was impressed with the results:

```
from dataclasses import dataclass
from dataclass_wizard import JSONSerializable, DumpMixin, LoadMixin

import re
from re import Pattern


class MyCustomLoadMixin(LoadMixin, DumpMixin):

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__()
        cls.register_custom_hooks()

    @classmethod
    def register_custom_hooks(cls):
        cls.register_load_hook(Pattern, cls.load_to_pattern)

    @staticmethod
    def load_to_str(o: str, *_) -> str:
        return o.upper()

    @staticmethod
    def load_to_pattern(o: Pattern, *_) -> Pattern:
        return re.compile(o)


# This line is not needed anymore, as `MyCustomLoadMixin`
# is only used as a Mixin class, and not directly.
# MyCustomLoadMixin.register_load_hook(Pattern, MyCustomLoadMixin.load_to_pattern)


@dataclass
class MyClass(JSONSerializable, MyCustomLoadMixin):
    regex: Pattern
    my_str: str

    @staticmethod
    def load_to_str(o: str, *_) -> str:
        return o.upper()

    @staticmethod
    def load_to_pattern(o: Pattern, *_) -> Pattern:
        return re.compile(o)


data = {"my_str": "my string", "regex": "[^/]+"}

c = MyClass.from_dict(data)
print(repr(c))
# prints:
#   MyClass(regex=re.compile('[^/]+'), my_str='MY STRING')
```

Here `MyCustomLoadMixin` is a re-usable Mixin class, and can be subclassed by any dataclasses that require custom loaders as in your regex case, for instance. Hope this helps! Documentation on this would be a huge improvement too.

Also, I recently opened [GitHub Discussions](https://github.com/rnag/dataclass-wizard/discussions), so going forward please don't hesitate to use it for Q/A and to get feedback from other users. Thanks!
