### ISSUE TITLE
[Question]: Is this project still active? 

### ISSUE THREAD

**Issue by sudhirbits** [rnag/dataclass-wizard#99]
[Question]: Is this project still active?

**Comment by rnag** [comment]
Hi @sudhirbits, thanks for opening this issue. I apologize as I have been on a long hiatus from the project. I'm going to do some playing around with codebase and look at current existing issues and PRs on the project.

I do certainly agree that the project has been inactive for too long, due entirely to negligence on my part, as well as life issues that have come up. I am certainly hopeful that this project can be active once again. 

As mentioned, I will look into the issues and PRs with fresh eyes, and determine what is a priority currently! In the meantime, do let me know if you had any questions or feedback about the project. Thanks!

**Comment by sudhirbits** [comment]
Thanks so much for your response. We liked this project for usage in our backend services, but unsure of whether this project was still active and the users and hence this ticket.
